# Generated by Django 2.0.7 on 2018-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='rango_dos',
            new_name='offset',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='rango_uno',
            new_name='pageSize',
        ),
        migrations.AddField(
            model_name='url',
            name='primera',
            field=models.BooleanField(default=False),
        ),
    ]
