# Generated by Django 2.0.7 on 2018-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20180805_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='offset',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='pageSize',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
