# Generated by Django 2.0.7 on 2018-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20180805_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='uuid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
