# Generated by Django 2.0.7 on 2018-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_tienda_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='url_pagina',
            field=models.URLField(default='https://www.ubereats.com/es-NZ/stores/'),
            preserve_default=False,
        ),
    ]
