# Generated by Django 2.0.7 on 2018-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_ciudad_url_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='request_payload',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
