# Generated by Django 2.0.7 on 2018-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20180807_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
